name: Delete Workflow Runs

on:
  workflow_dispatch:


jobs:
  delete_runs:
    runs-on: ubuntu-latest
  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test
        run: |
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer  ${{ secrets.TOKEN }}" \
            https://api.github.com/repos/schawnndubois/DevOps-Portfolio/contents/.github/workflows/Netlify Deploy \
            -d '{
            "message": "Disable workflow",
            "content": "'$(echo -n "enabled: false" | base64)'",
            "sha": "the-sha-of-your-existing-file"
            }'
