name: Delete Workflow Runs

on:
  workflow_dispatch:
  workflow_run:
    workflows: "https://api.github.com/repos/schawnndubois/DevOps-Portfolio/actions/workflows/main.yml"  # Replace with your actual workflow name
    types:
      - completed

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List workflow runs
        run: |
          runs=$(gh run list --limit 500 --workflow 'https://api.github.com/repos/schawnndubois/DevOps-Portfolio/actions/workflows/main.yml' --json databaseId | jq -r '.[] | .databaseId | @sh')
          echo "Workflow runs to delete: $runs"

      - name: Delete workflow runs
        run: |
          echo "$runs" | xargs -I{} gh run delete {}
